# ====config 设置====
# 依赖组件
gems: [jekyll-paginate]

# 本地服务器 
host: 0.0.0.0
port: 4001

# 时区
timezone: Asia/Shanghai

# 代码高亮模式
highlighter: rouge

# 根目录设置
# 如果是根目录, 不要填写'/', 直接留空就行
# 如果是非根目录访问, 如http://abc.com/blog, 此处填写'/blog'
baseurl:

# 分页设置
paginate: 10

# 分页形式
paginate_path: "page:num"


# ====site info 站点信息====
# 标题: 在左侧顶栏显示, 以及底部版权位置显示
title: 我的博客

# 兴趣爱好描述: 在左侧顶栏标题下显示, 同时作为页面meta标签内使用(SEO)
bio: 这是一个基于jekyll的博客

# 展示头像图片地址
user_img: 

# 站点描述和关键词 仅作用于页面meta标签使用(SEO)
description: 
keywords: jekyll,simack,博客



# ====sidebar links 侧边栏链接====
# 站内导航
# 需要使用'/'开头
menusLinks:
  - title: 首页
    url: /
  - title: 关于
    url: /about.html

# 栏目列表
# 需要手动编写, 放置在categories目录下
categoryLinks:
  - title: 杂谈
    url: /categories/normal.html
  - title: 学习
    url: /categories/study.html

# 友情链接(此链接在新窗口打开)
friendLinks:
  - title: simack
    url: https://github.com/yukapril/jekyll-theme-simack


# 多说配置
# status 是否开启多说，true开启，false关闭
# name 你在多说分配的short_name
duoshuo:
  status: false
  name:


# 访问统计
# 直接写入js链接即可
page_analysis:
  common:
# 备案信息
miibeian: 